debug: true
appToken: 2fe9a70a-46f2-4d00-88f2-6f66ed903426
database: development.db
port: :3500
fakeMailer: true
smtp:
    host: smtp.mailgun.org
    port: 587
    login: joe.doe@mg.example.com
    password: bbp1mrl6TJLh
    from: joe.doe@example.com
    cc: []
    bcc: []
